version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:5000  # Fixed internal URL
      - VITE_DEV_API_URL=http://localhost:3001/backend  # For development

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:5000"  # External:3001 → Internal:5000
    environment:
      - PORT=5000  # Must match internal container port